config/routes.rb
AspergersDating::Application.routes.draw do
  devise_for :users

  devise_for :users, :controllers => {:registrations => "users"}
  
  devise_scope :user do
    get "users/new_user", :to => "users#new", :as => :sign_up
    get "users/browse", :to => "profiles#browse", :as => :browse
    get "users/:id", :to => "profiles#show", :as => :user
    get "inbox", :to => "messages#inbox", :as => :inbox
    get "message/:id", :to => "messages#message", :as => :message
    get "delete_message/:id", :to => "messages#delete_message", :as => :delete_message
#    post "send_message", :to => "messages#send", :as => :send_message
  end
  
  match "send_message" => "messages#send_message"
  match "reply_message" => "messages#reply_message"
#  match "remove_message" => "messages#delete_message"
#  match "messages/inbox" => "messages#inbox" #"home#index" #"messaging#inbox"
#  match "messages/message/:id" => "messages#message" #"home#index" #"messaging#show"

  root :to => "home#index"
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :authenticate_user!
  
  def inbox
    @messages = current_user.received_messages
  end
  
  def message
    @message = current_user.received_messages.with_id(params[:id]).first
    @message.mark_as_read
    @sender = User.find_by_id(@message.sent_messageable_id)
  end
  
  def send_message
    #TODO: error-checking and error handling
    
    @recipient = User.find_by_id(params[:recipient_id])
    
    current_user.send_message(@recipient, params[:topic], params[:body])

    respond_to do |format|
      format.js {render :nothing => true}
    end
  end
  
  def reply_message
    #TODO: error-checking and error handling
    
    @recipient = User.find_by_id(params[:recipient_id])
    
    current_user.send_message(@recipient, "Re: " + params[:topic], params[:body])
    
    respond_to do |format|
      format.js {render :nothing => true}
    end
  end
  
  def delete_message
    #TODO: error-checking and error handling
    
    @message = current_user.received_messages.with_id(params[:id]).first
    current_user.delete_message(@message)
    
    respond_to do |format|
      format.html {redirect_to inbox_path}
    end
  end
end

app/views/messages/inbox.html.erb
<div id="left_column">
  <h4 id="content_title_bar">Inbox</h4>
  <div id="newest_users">
    <table width="100%">
      <% unless @messages.empty? %>
        <tr>
          <th>Topic</th>
          <th>Sender</th>
          <th>Received</th>
          <th></th>
        </tr>
          <% @messages.each do |f| %>
            <tr>
              <td><%= link_to f.topic, message_path(f) %></td>
              <td><%= link_to User.find_by_id(f.sent_messageable_id).username, user_path(f.sent_messageable_id) %></td>
              <td><%= f.created_at.strftime("%m/%d/%Y %I:%M %p") %></td>
              <td><%= link_to "Delete", delete_message_path(f) %></td>
            </tr>
          <% end %>
      <% else %>
        <tr>
          <td>No messages!</td>
        </tr>
      <% end %>
    </table>
  </div>
</div>
<div id="right_column">
  <h4 id="content_title_bar">Advertisement</h4>
  <div id="tall_banner_container">
    <div id="tall_banner">
    </div>
  </div>
</div>

app/views/messages/message.html.erb
<script type="text/javascript">
  $(document).ready(function(){
    $("#sending, #sent").hide();
    $(".reply_message_button").click(function(){
      $(".reply_message_form_form").hide();
      $("#sending").show();
      
      $.post("/reply_message", $("form.reply_message_form_form").serialize(), function(data) {
        console.log(data);
      })
      .done(function() {
        console.log("success!");
        $("#sending").hide();
        $("#sent").show();
      })
      .fail(function() {
        console.log("failed!"); //TODO: error-handling, message to user in GUI
      });
      
      return false; //prevent form from submitting
    });
  });
</script>
<div id="left_column">
  <h4 id="content_title_bar">Message</h4>
  <div id="message_message">
    <p>
      <%= @message.body %><br/>
      <%= button_to "Delete Message", delete_message_path(@message), :method => "get" %>
    </p>
  </div>
  <h4 id="content_title_bar">Want to reply to <%= @sender.username %>?</h4>
  <div id="reply_message_form">
    <%= form_tag reply_message_path, :class => "reply_message_form_form", :remote => true do %>
      <%= hidden_field_tag :topic, @message.topic %>
      Message: <%= text_area_tag :body %><br/>
      <%= hidden_field_tag :recipient_id, @sender.id %>
      <%= submit_tag "Send Message", :class => "reply_message_button" %>
    <% end %>
    <p id="sending">Sending...</p>
    <p id="sent">Successfully sent!</p>
  </div>
</div>
<div id="right_column">
  <h4 id="content_title_bar">Sender Info</h4>
  <div id="basic_info">
    <table id="basic_info_table">
      <tbody>
        <tr>
          <td class="left">Username</td>
          <td class="right"><%= @sender.username %></td>
        </tr>
        <tr>
          <td class="left">Location</td>
          <td class="right"><%= @sender.zipcode %></td>
        </tr>
<!--        <tr>
          <td class="left">Last Login</td>
          <td class="right"><%= @sender.last_sign_in_at %></td>
        </tr>-->
        <tr>
          <td class="left">Status</td>
          <td class="right"><%= @sender.marital_status %></td>
        </tr>
        <tr>
          <td class="left">Age</td>
          <td class="right"><%= @sender.age %></td>
        </tr>
        <tr>
          <td class="left">Height</td>
          <td class="right"><%= @sender.height_feet %>' <%= @sender.height_inches %>"</td>
        </tr>
        <tr>
          <td class="left">Weight</td>
          <td class="right"><%= @sender.weight %></td>
        </tr>
        <tr>
          <td class="left">Smokes</td>
          <td class="right"><%= @sender.smoke %></td>
        </tr>
        <tr>
          <td class="left">Drinks</td>
          <td class="right"><%= @sender.drink %></td>
        </tr>
        <tr>
          <td class="left">Religion</td>
          <td class="right"><%= @sender.religion %></td>
        </tr>
        <tr>
          <td class="left">Sign</td>
          <td class="right"><%= @sender.sign %></td>
        </tr>
      </tbody>
    </table>
  </div>
  <h4 id="content_title_bar">Advertisement</h4>
  <div id="tall_banner_container">
    <div id="tall_banner">
    </div>
  </div>
</div>