config/routes.rb
AspergersDating::Application.routes.draw do
  devise_for :users

  devise_for :users, :controllers => {:registrations => "users"}
  
  devise_scope :user do
    get "users/new_user", :to => "users#new", :as => :sign_up
    get "users/browse", :to => "profiles#browse", :as => :browse
    get "users/:id", :to => "profiles#show", :as => :user
    get "inbox", :to => "messages#inbox", :as => :inbox
    get "message/:id", :to => "messages#message", :as => :message
    get "delete_message/:id", :to => "messages#delete_message", :as => :delete_message
#    post "send_message", :to => "messages#send", :as => :send_message
  end
  
  match "send_message" => "messages#send_message"
  match "reply_message" => "messages#reply_message"
#  match "remove_message" => "messages#delete_message"
#  match "messages/inbox" => "messages#inbox" #"home#index" #"messaging#inbox"
#  match "messages/message/:id" => "messages#message" #"home#index" #"messaging#show"

  root :to => "home#index"
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :authenticate_user!

  def show
    @user = User.find(params[:id])
  end
  
  def browse
    #assemble genders for search
    if params[:gender].present?
      genders = []
      params[:gender].each do |n|
        genders.push(n)
      end
    else
      genders = %w{male female trans genderqueer}
    end

    #assemble diag statuses for search
    if params[:diagnosis].present?
      diagnoses = []
      params[:diagnosis].each do |n|
        diagnoses.push(n)
      end
    else
      diagnoses = %w{confirmed self-diagnosed suspected nt}
    end

    #assemble orientations for search
    if params[:orientation].present?
      orientations = []
      params[:orientation].each do |n|
        orientations.push(n)
      end
    else
      orientations = %w{straight gay bisexual queer trans asexual}
    end

    #assemble looking fors for search
    #
    #revisit this because people can look for more than one thing
    #
    if params[:lookingfor].present?
      lookingfors = []
      params[:lookingfor].each do |n|
        lookingfors.push(n)
      end
    else
      lookingfors = %w{love dating friends hook-ups}
    end

    #assemble social preferences for search
    if params[:socialpref].present?
      socialprefs = []
      params[:socialpref].each do |n|
        socialprefs.push(n)
      end
    else
      socialprefs = %w{social sometimes one-on-one small-groups}
    end
    
    #assemble smoker preferences for search
    if params[:smoke].present?
      smokes = []
      params[:smoke].each do |n|
        smokes.push(n)
      end
    else
      smokes = %w{yes no}
    end
    
    #assemble smoker preferences for search
    if params[:drink].present?
      drinks = []
      params[:drink].each do |n|
        drinks.push(n)
      end
    else
      drinks = %w{yes no}
    end

    puts "-------------"
    puts "-------------"
    if params[:place].present?
#      @users = User.near(params[:place], params[:distance][0][:miles], :order => :distance).paginate(:page => params[:page])
      @users = User.where{(gender.eq_any genders) & (diagnostic_status.eq_any diagnoses) & 
        (orientation.eq_any orientations) & (looking_for.like_any lookingfors) & (social_preference.eq_any socialprefs) & 
        (smoke.eq_any smokes) & (drink.eq_any drinks)}.near(params[:place], params[:distance][0][:miles]).paginate(:page => params[:page])
    else
      @users = User.paginate(:page => params[:page])
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/browse.html.erb
<div id="left_column">
	<h4 id="content_title_bar">Search Criteria</h4>
	<div id="search_criteria">
		<p>
			<%= form_tag browse_path, :method => :get do %>
				<table>
					<tr>
						<td>City and State or ZIP / Miles:</td>
						<td>
							<%= text_field_tag :place, params[:place] %>
							<%= select("distance", "miles", %w[5 10 15 20 25 50 100 250 500 1000 5000 24901.55], {}, { :index => nil }) %>
						</td>
					</tr>
					<tr>
						<td colspan="2">
							Gender:
							<%= field_set_tag do %>
								<table cellpadding="0" cellspacing="0" border="0">
									<tr>
										<td><%= check_box_tag 'gender[]', 'male'%> Male</td>
										<td><%= check_box_tag 'gender[]', 'female'%> Female</td>
									</tr>
									<tr>
										<td><%= check_box_tag 'gender[]', 'genderqueer' %> Genderqueer</td>
										<td><%= check_box_tag 'gender[]', 'trans' %> Transgendered</td>
										<td></td>
									</tr>
								</table>
							<% end %>
						</td>
					</tr>
	<!--				<tr>
						<td colspan="2">
							Diagnostic Status:
							<%= field_set_tag do %>
								<table cellpadding="0" cellspacing="0" border="0">
									<tr>
										<td><%= check_box_tag 'diagnosis[]', 'confirmed' %> Confirmed</td>
										<td><%= check_box_tag 'diagnosis[]', 'self-diagnosed' %> Self-Diagnosed</td>
									</tr>
									<tr>
										<td><%= check_box_tag 'diagnosis[]', 'suspected' %> Suspected</td>
										<td><%= check_box_tag 'diagnosis[]', 'nt' %> Neurotypical</td>
									</tr>
								</table>
							<% end %>
						</td>
		</tr>-->
					<tr>
						<td colspan="2">
							Orientation:
							<%= field_set_tag do %>
								<table cellpadding="0" cellspacing="0" border="0">
									<tr>
										<td><%= check_box_tag 'orientation[]', 'straight' %> Straight</td>
										<td><%= check_box_tag 'orientation[]', 'gay' %> Gay</td>
										<td><%= check_box_tag 'orientation[]', 'bisexual' %> Bisexual</td>
									</tr>
									<tr>
										<td><%= check_box_tag 'orientation[]', 'queer' %> Queer</td>
										<td><%= check_box_tag 'orientation[]', 'trans' %> Trans</td>
										<td><%= check_box_tag 'orientation[]', 'asexual' %> Asexual</td>
										<td></td>
									</tr>
								</table>
							<% end %>
						</td>
					</tr>
	<!--				<tr>
						<td colspan="2">
							Looking For:
							<%= field_set_tag do %>
								<table cellpadding="0" cellspacing="0" border="0">
									<tr>
										<td><%= check_box_tag 'lookingfor[]', 'love' %> Love</td>
										<td><%= check_box_tag 'lookingfor[]', 'dating' %> Dating</td>
										<td><%= check_box_tag 'lookingfor[]', 'friends' %> Friends</td>
										<td><%= check_box_tag 'lookingfor[]', 'hook-ups' %> Hook-Ups</td>
									</tr>
								</table>
							<% end %>
						</td>
		</tr>-->
	<!--				<tr>
						<td colspan="2">
							Social Preference:
							<%= field_set_tag do %>
								<table cellpadding="0" cellspacing="0" border="0">
									<tr>
										<td><%= check_box_tag 'socialpref[]', 'social' %> Social</td>
										<td><%= check_box_tag 'socialpref[]', 'sometimes' %> Sometimes Social</td>
									</tr>
									<tr>
										<td><%= check_box_tag 'socialpref[]', 'small-groups' %> Small Groups Only</td>
										<td><%= check_box_tag 'socialpref[]', 'one-on-one' %> One on One</td>
									</tr>
								</table>
							<% end %>
						</td>
		</tr>-->
					<tr>
						<td colspan="2">
							Smoker:
							<%= field_set_tag do %>
								<table cellpadding="0" cellspacing="0" border="0">
									<tr>
										<td><%= check_box_tag 'smoke[]', 'yes' %> Yes</td>
										<td><%= check_box_tag 'smoke[]', 'no' %> No</td>
									</tr>
								</table>
							<% end %>
						</td>
					</tr>
					<tr>
						<td colspan="2">
							Drinker:
							<%= field_set_tag do %>
								<table cellpadding="0" cellspacing="0" border="0">
									<tr>
										<td><%= check_box_tag 'drink[]', 'yes' %> Yes</td>
										<td><%= check_box_tag 'drink[]', 'no' %> No</td>
									</tr>
								</table>
							<% end %>
						</td>
					</tr>
					<tr>
						<td></td>
						<td><%= submit_tag "Browse", :name => nil %></td>
					</tr>
				</table>
			<% end %>
		</p>
	</div>
	<h4 id="content_title_bar">Results</h4>
	<div id="search_results">
		<% for user in @users %>
			<div id="result_badge">
				<div id="top_badge">
					<div id="user_pic">
						<% if user.user_pictures.count > 0 %>
							<%= image_tag user.user_pictures.first.picture.url(:thumb) %>
						<% else %>
							<%= image_tag "no_pic_thumb.jpg" %>
						<% end %>
					</div>
					<div id="user_info">
						<b><%= link_to "#{user.username}", user_path(user) %></b><br />
						<%= user.age %> / <%= user.gender %> / <%= user.orientation %> / <%= user.marital_status %><br />
						48116
					</div>
				</div>
				<div id="bottom_badge">
					<p><b><font color="#1c699d">About:</font></b></v> <%= truncate(user.about, :length => 250) %></p>
				</div>
			</div>
		<% end %>
		<div id="search_pagination">
			<%= will_paginate @users %>
		</div>
<!-- 		<p>
			<table>
				<tr>
					<th></th>
					<th>Username</th>
					<th>About</th>
				</tr>
				<% for user in @users %>
					<tr>
						<td width="100" height="100">
							<% if user.user_pictures.count > 0 %>
								<%= image_tag user.user_pictures.first.picture.url(:thumb) %>
							<% else %>
								<%= image_tag "no_pic_thumb.jpg" %>
							<% end %>
						</td>
						<td><%= user.username %></td>
						<td><%= user.about %></td>
					</tr>
				<% end %>
			</table>
			<%= will_paginate @users %>
		</p> -->
	</div>
</div>
<div id="right_column">
	<h4 id="content_title_bar">Basic Search</h4>
	<div id="basic_search">
		<%= form_tag browse_path, :method => :get do %>
			<table>
				<tr>
					<td>Username:</td>
					<td><%= text_field_tag :username, params[:username], :size => 16 %></td>
				</tr>
				<tr>
					<td>Keyword:</td>
					<td><%= text_field_tag :keyword, params[:keyword], :size => 16 %></td>
				</tr>
				<tr>
					<td></td>
					<td><%= submit_tag "Basic Search", :name => nil %></td>
				</tr>
			</table>
		<% end %>
	</div>
	<h4 id="content_title_bar">Advertisement</h4>
	<div id="tall_banner_container">
		<div id="tall_banner">
		</div>
	</div>
</div>

app/views/profiles/show.html.erb
<script type="text/javascript">
  $(document).ready(function(){
    $("#sending, #sent").hide();
    $(".send_message_button").click(function(){
      $(".send_message_form_form").hide();
      $("#sending").show();
      
      $.post("/send_message", $("form.send_message_form_form").serialize(), function(data) {
        console.log(data);
      })
      .done(function() {
        console.log("success!");
        $("#sending").hide();
        $("#sent").show();
      })
      .fail(function() {
        console.log("failed!"); //TODO: error-handling, message to user in GUI
      });
      
      return false; //prevent form from submitting
    });
  });
</script>
<div id="left_column">
		<% if @user.user_pictures.count > 0 %>
			<h4 id="content_title_bar"> Pictures</h4>
			<div id="pictures">
				<% @user.user_pictures.each do |n| %>
					<span class="picture_box"><%= image_tag n.picture.url(:thumb) %></span>			 
				<% end %>
			</div>
		<% end %>
	<h4 id="content_title_bar">Essays</h4>
	<div id="profile_essays">
		<dl>
			<dt>About Me</dt>
			<dd><%= @user.about %></dd>
			<dt>My Diagnosis</dt>
			<dd><%= @user.diagnosis_story %></dd>
			<dt>Special Needs</dt>
			<dd><%= @user.special_needs %></dd>
			<dt>Things I Do</dt>
			<dd><%= @user.things_i_do %></dd>
			<dt>Things I Don't Do</dt>
			<dd><%= @user.things_i_dont_do %></dd>
			<dt>Obsessions</dt>
			<dd><%= @user.obsessions %></dd>
			<dt>Who I'd Like To Meet</dt>
			<dd><%= @user.who_id_like_to_meet %></dd>
			<dt>7 Things I Adore</dt>
			<dd><%= @user.seven_things_i_adore %></dd>
		</dl>
	</div>
	<h4 id="content_title_bar">Want to talk to <%= @user.username %>?</h4>
  <div id="send_message_form">
    <%= form_tag send_message_path, :class => "send_message_form_form", :remote => true do %>
      Subject: <%= text_field_tag :topic %><br/>
      Message: <%= text_area_tag :body %><br/>
      <%= hidden_field_tag :recipient_id, @user.id %>
      <%= submit_tag "Send Message", :class => "send_message_button" %>
    <% end %>
    <p id="sending">Sending...</p>
    <p id="sent">Successfully sent!</p>
  </div>
</div>
<div id="right_column">
	<h4 id="content_title_bar">Basic Info</h4>
	<div id="basic_info">
		<table id="basic_info_table">
			<tbody>
				<tr>
					<td class="left">Username</td>
					<td class="right"><%= @user.username %></td>
				</tr>
				<tr>
					<td class="left">Location</td>
					<td class="right"><%= @user.zipcode %></td>
				</tr>
<!--				<tr>
					<td class="left">Last Login</td>
					<td class="right"><%= @user.last_sign_in_at %></td>
				</tr>-->
				<tr>
					<td class="left">Status</td>
					<td class="right"><%= @user.marital_status %></td>
				</tr>
				<tr>
					<td class="left">Age</td>
					<td class="right"><%= @user.age %></td>
				</tr>
				<tr>
					<td class="left">Height</td>
					<td class="right"><%= @user.height_feet %>' <%= @user.height_inches %>"</td>
				</tr>
				<tr>
					<td class="left">Weight</td>
					<td class="right"><%= @user.weight %></td>
				</tr>
				<tr>
					<td class="left">Smokes</td>
					<td class="right"><%= @user.smoke %></td>
				</tr>
				<tr>
					<td class="left">Drinks</td>
					<td class="right"><%= @user.drink %></td>
				</tr>
				<tr>
					<td class="left">Religion</td>
					<td class="right"><%= @user.religion %></td>
				</tr>
				<tr>
					<td class="left">Sign</td>
					<td class="right"><%= @user.sign %></td>
				</tr>
			</tbody>
		</table>
	</div>
	<h4 id="content_title_bar">Advertisement</h4>
	<div id="tall_banner_container">
		<div id="tall_banner">
		</div>
	</div>
</div>